### PR TITLE
Rewrite coc_extensions

### PR DESCRIPTION
**Pull request by liuchengxu**
- The `sink` action is `ToggleExtension`.
- Action dialog options:  `Uninstall`, `Reload`, `Deactivate` and `Toggle` extension.

Close https://github.com/vn-ki/coc-clap/issues/4

### CODE REVIEW

**Comment by vn-ki** [comment]
Thanks for this! I was trying to find some time to implement actions.

**Comment by glepnir** [comment]
@liuchengxu  got error
```viml
vim-clap: Fail to load provider: coc_extensions, E:Vim(let):E121: Undefined variable: g:clap#provider#coc_extensions#
```

**Comment by liuchengxu** [comment]
@glepnir Ensure you are using the latest clap and coc-clap.

**Comment by glepnir** [comment]
@liuchengxu  yes i updated it then got this.

**Comment by liuchengxu** [comment]
@glepnir Can't reproduce. File an issue at clap if you can reproduce it.

**Comment by glepnir** [comment]
@liuchengxu  ok i found problem.

**Pull request merged**
